In [1]:
import tensorflow as tf
from tensorflow import keras
import pathlib
import numpy as np

# Cambiar rutas para poder probar un dataset cualquiera
test_dir = '.\\test'

IMG_SIZE = (128, 128) 
BATCH_SIZE = 32

dataset = keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="binary"
)

Found 160 files belonging to 2 classes.


In [2]:
print("\n--- Tipo de Dataset ---")
print(type(dataset))

print("\n--- Elementos del Dataset ---")
for elem in dataset:
    print(elem)


--- Tipo de Dataset ---
<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>

--- Elementos del Dataset ---
(<tf.Tensor: shape=(32, 128, 128, 3), dtype=float32, numpy=
array([[[[254.      , 255.      , 255.      ],
         [254.      , 255.      , 255.      ],
         [254.      , 255.      , 255.      ],
         ...,
         [252.      , 255.      , 255.      ],
         [252.      , 255.      , 255.      ],
         [252.      , 255.      , 255.      ]],

        [[255.      , 255.      , 255.      ],
         [255.      , 255.      , 255.      ],
         [255.      , 255.      , 255.      ],
         ...,
         [254.      , 255.      , 255.      ],
         [254.      , 255.      , 255.      ],
         [254.      , 255.      , 255.      ]],

        [[254.35547 , 252.85156 , 253.71094 ],
         [255.      , 253.4961  , 254.35547 ],
         [255.      , 253.92578 , 254.78516 ],
         ...,
         [254.      , 254.14062 , 254.14062 ],
         [254.      

In [3]:
print("\n--- Primer elemento del Dataset ---")
print(dataset.take(1))


--- Primer elemento del Dataset ---
<_TakeDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [4]:
# Inspeccionar el primer batch (el dataset contiene varios batches... con tamaño especificado arriba)
print("\n--- Primer Batch de Imágenes ---")
for batch, labels in dataset.take(1):
    print("Forma del batch:", batch.shape)
    print("Etiquetas:", labels) # labels.numpy() convierte de tf.Tensor a array de Numpy


--- Primer Batch de Imágenes ---
Forma del batch: (32, 128, 128, 3)
Etiquetas: tf.Tensor(
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]], shape=(32, 1), dtype=float32)


In [5]:
# Obtener tamaño del dataset
dataset_size = dataset.reduce(0, lambda x, _: x + 1).numpy()
print(f"\n--- Tamaño del Dataset (en batches...): {dataset_size} ---")


--- Tamaño del Dataset (en batches...): 5 ---


In [6]:
# Ver la estructura del dataset (MUY IMPORTANTE)
print("\n--- Estructura de los elementos ---")
print(dataset.element_spec)


--- Estructura de los elementos ---
(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [7]:
# Ejemplo para visualizar las dimensiones totales (en este ejemplo el tensor principal tiene 5 dim)
data_numpy = np.array([x.numpy() for x, y in dataset])
labels_numpy = np.array([y.numpy() for x, y in dataset])

print("Forma de los datos (NumPy):", data_numpy.shape)
print("Forma de las etiquetas en NumPy:", labels_numpy.shape)

Forma de los datos (NumPy): (5, 32, 128, 128, 3)
Forma de las etiquetas en NumPy: (5, 32, 1)


In [8]:
# Ejemplo para inspeccionar las dimensiones que tiene 1 batch
for x_batch, y_batch in dataset.take(1):  # Desempaquetar la tupla
    print("Forma de un batch de imágenes:", x_batch.shape)
    print("Forma de un batch de etiquetas:", y_batch.shape)

Forma de un batch de imágenes: (32, 128, 128, 3)
Forma de un batch de etiquetas: (32, 1)
